### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: sites

### ISSUE THREAD

**Issue by barrjam** [microsoftgraph/msgraph-cli#322]
```
cd ~/bin
gunzip msgraph-cli-osx-x64-1.0.0-preview.1.tar.gz 
xvf msgraph-cli-osx-x64-1.0.0-preview.1.tar 
export PATH="~/bin:${PATH}"

bash-5.1$ mgc sites
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: sites
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(Command command)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CommandLineConfiguration configuration, Boolean inferRootCommand)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   at Microsoft.Graph.Cli.Program.Main(String[] args) in /home/vsts/work/1/s/src/Program.cs:line 104
   at Microsoft.Graph.Cli.Program.<Main>(String[] args)
```

Same with absolute path

```
bash-5.1$ ~/bin/mgc sites
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: sites
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(Command command)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CommandLineConfiguration configuration, Boolean inferRootCommand)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   at Microsoft.Graph.Cli.Program.Main(String[] args) in /home/vsts/work/1/s/src/Program.cs:line 104
   at Microsoft.Graph.Cli.Program.<Main>(String[] args)
```

**Comment by calebkiage** [comment]
Hello @barrjam, thank you for raising this issue. It's actually a known issue that was first reported here #316 and we're working on it.

**Comment by calebkiage** [comment]
A workaround has been implemented in [preview 2](https://github.com/microsoftgraph/msgraph-cli/releases/tag/v1.0.0-preview.2) release
