### ISSUE TITLE
mgc login with client ID, client secret, and tenant ID returns invalid client

### ISSUE THREAD

**Issue by cadenmarchese** [microsoftgraph/msgraph-cli#383]
mgc is configured to take `--strategy Environment` (such as service principal credentials) to login:
```
mgc login --help                                                                                                                                                                                                     
Description:
  Login and store the session for use in subsequent commands

Usage:
  mgc login [options]

Options:
  --scopes <scopes>                                    The login scopes e.g. User.Read. Required scopes can be found in the docs linked against each verb (get, list, create...) command.
  --client-id <client-id>                              The client (application) id
  --tenant-id <tenant-id>                              The tenant (directory) id
  --certificate-name <certificate-name>                The name of your certificate (e.g. CN=MyCertificate). The certificate will be retrieved from the current user's certificate store.
  --certificate-thumb-print <certificate-thumb-print>  The thumbprint of your certificate. The certificate will be retrieved from the current user's certificate store.
  --strategy <strategy>                                The authentication strategy to use. [default: DeviceCode]

                                                         Available strateges:
                                                           DeviceCode:         Use a device code to log in.
                                                           InteractiveBrowser: Open a browser on this computer to log in.
                                                           ClientCertificate:  Use a certificate stored on this computer's certificate store to sign in. The certificate must have a private key available.
                                                           ManagedIdentity: Use the managed identity of the Azure resource to log in.
                                                           Environment:        Use values stored in environment variables to log in.
                                                             Supported environment variables:
                                                               AZURE_TENANT_ID
                                                               AZURE_CLIENT_ID
                                                               AZURE_CLIENT_SECRET
                                                               AZURE_CLIENT_CERTIFICATE_PATH
                                                               AZURE_CLIENT_CERTIFICATE_PASSWORD
                                                               AZURE_CLIENT_SEND_CERTIFICATE_CHAIN

                                                       NOTE: The strategy value is not case sensitive. Therefore, --strategy DeviceCode and --strategy devicecode are equivalent.
  --headers <headers>                                  Allows adding custom headers to the request. The option can be used multiple times to add multiple headers. e.g. --headers key1=value1 --headers key2=value2
  -?, -h, --help                                       Show help and usage information
  --debug                                              Enable debug output
```
However, setting env vars `AZURE_TENANT_ID`, `AZURE_CLIENT_ID`, and `AZURE_CLIENT_SECRET` results in an invalid client when attempting to use the credentials:
```
mgc applications create --body '{"displayName": "Display name"}'                                                                                                                                                             

[Error] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:40 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8103 [2023-11-07 15:38:23Z - <redacted>] The current authority is targeting the /common or /organizations endpoint which is not recommended. See https://aka.ms/msal-net-client-credentials for more details.
[Error] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:40 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8103 [2023-11-07 15:38:24Z - <redacted>] === Token Acquisition (1004) failed.
	Host: login.microsoftonline.com.
[Error] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:40 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8103 [2023-11-07 15:38:24Z - <redacted>] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: invalid_client
HTTP StatusCode 401
CorrelationId <redacted>

[Error] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:40 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8103 [2023-11-07 15:38:24Z - <redacted>] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: invalid_client
HTTP StatusCode 401
CorrelationId <redacted>

   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders, Func`2 onBeforePostRequestHandler)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
Unhandled exception: Azure.Identity.AuthenticationFailedException: ClientSecretCredential authentication failed: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '<redacted>'. Trace ID: <redacted> Correlation ID: <redacted> Timestamp: 2023-11-07 15:38:24Z
 ---> MSAL.NetCore.4.56.0.0.MsalServiceException:
	ErrorCode: invalid_client
Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '<redacted>'. Trace ID: <redacted> Correlation ID: <redacted> Timestamp: 2023-11-07 15:38:24Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders, Func`2 onBeforePostRequestHandler)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ClientSecretCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
	StatusCode: 401
	ResponseBody: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '<redacted>'. Trace ID: <redacted> Correlation ID: <redacted> Timestamp: 2023-11-07 15:38:24Z","error_codes":[7000215],"timestamp":"2023-11-07 15:38:24Z","trace_id":"<redacted>","correlation_id":"<redacted>","error_uri":"https://login.microsoftonline.com/error?code=7000215"}
	Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: <redacted>
x-ms-request-id: <redacted>
x-ms-ests-server: 2.1.16729.5 - NCUS ProdSlices
x-ms-clitelem: 1,7000215,0,,
X-XSS-Protection: 0
Set-Cookie: fpc=AmD5PQZ4s0VAgjc0rIH5yV8ZlJq2AQAAAO9Q3NwOAAAA; expires=Thu, 07-Dec-2023 15:38:24 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Tue, 07 Nov 2023 15:38:23 GMT

   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
   at Azure.Identity.ClientSecretCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Microsoft.Graph.Cli.Core.Authentication.EnvironmentCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken) in /_/src/Microsoft.Graph.Cli.Core/Authentication/EnvironmentCredential.cs:line 120
   at Microsoft.Kiota.Authentication.Azure.AzureIdentityAccessTokenProvider.GetAuthorizationTokenAsync(Uri uri, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken)
   at Microsoft.Kiota.Abstractions.Authentication.BaseBearerTokenAuthenticationProvider.AuthenticateRequestAsync(RequestInformation request, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims, Boolean isStreamResponse)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at ApiSdk.Applications.ApplicationsRequestBuilder.<>c__DisplayClass2_0.<<BuildCreateCommand>b__1>d.MoveNext() in /home/vsts/work/1/s/src/generated/Applications/ApplicationsRequestBuilder.cs:line 113
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c__DisplayClass0_0.<<UseRequestAdapter>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Graph.Cli.Program.<>c.<<Main>b__2_2>d.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 74
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Graph.Cli.Program.<>c__DisplayClass3_0.<<BuildCommandLine>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 137
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c.<<RegisterCommonServices>b__2_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c__DisplayClass3_0.<<RegisterHeadersOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
The above is an example from Mac, but it's also reproducible on Linux.

**Comment by calebkiage** [comment]
Hello @cadenmarchese, thank you for reporting this issue. I'm unable to reproduce the error you've reported. However, going through the stack trace and error message, I notice that the error gives a hint of what might be happening:

> Invalid client secret provided. _**Ensure the secret being sent in the request is the client secret value, not the client secret ID**_

You should find the client secret under the `Value` column. The value column is only visible right after creating a secret.
![image](https://github.com/microsoftgraph/msgraph-cli/assets/747955/7ec19239-6e7e-4a31-a9cf-7cb88c044439)

**Comment by cadenmarchese** [comment]
@calebkiage thanks for your quick response! I would suspect that as well, but I can create an app just fine using `az` + those service principal credentials:
```
az login --service-principal --tenant $AZURE_TENANT_ID --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET

az ad app create --display-name appname
(it works!)
```
If I do the same with `mgc applications create --body` after a `--strategy Environment` login, I get the invalid client error.

Looking at the [documentation for az ad app](https://learn.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest), I see it also appears to be using the MSGraph API to create the app, so I'm not sure why one would be failing and the other succeeding.

**Comment by calebkiage** [comment]
That's interesting.

Does providing the client id and client secret to the login command work?

For example:

```
mgc login --strategy Environment --tenant-id <tenant id> --client-id <client id>
```

**Comment by cadenmarchese** [comment]
That appears to work, thanks! It wasn't clear from the help page that they were needed.

**Comment by calebkiage** [comment]
@cadenmarchese, it's actually a bug. The next release should have a fix for it. Thanks for reporting it.

**Comment by z-sourcecode** [comment]
> mgc login --strategy Environment --tenant-id <tenant id> --client-id <client id>

Actually it didn't work for me - i get:

Authentication failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot_

Double check I have all AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET populated (AZURE_CLIENT_SECRET - has the value not the name)

Does mgc support login without certificate? i have no issues login to Az cli

**Comment by calebkiage** [comment]
Hello @z-sourcecode, the `--tenant-id` and `--client-id` shouldn't be provided when using environment login. The suggestion was a workaround for a bug. Just set the environment variables and run `mgc login --strategy Environment`
