### ISSUE TITLE
Sub-command crashes on Mac Arm64 release

### ISSUE THREAD

**Issue by bgmonroe** [microsoftgraph/msgraph-cli#386]
While not exhaustive, some sub-commands are crashing with "Unhandled exception: ApiSdk.Models.ODataErrors.ODataError: Exception of type 'ApiSdk.Models.ODataErrors.ODataError' was thrown." errors.

Ex. 1:
``` sh
$ mgc identity get
Unhandled exception: ApiSdk.Models.ODataErrors.ODataError: Exception of type 'ApiSdk.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at ApiSdk.Identity.IdentityRequestBuilder.<>c__DisplayClass3_0.<<BuildGetCommand>b__1>d.MoveNext() in /home/vsts/work/1/s/src/generated/Identity/IdentityRequestBuilder.cs:line 141
```

Ex. 2:
``` sh
$ mgc role-management directory get
Unhandled exception: ApiSdk.Models.ODataErrors.ODataError: Exception of type 'ApiSdk.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at ApiSdk.RoleManagement.DirectoryNamespace.DirectoryRequestBuilder.<>c__DisplayClass1_0.<<BuildGetCommand>b__1>d.MoveNext() in /home/vsts/work/1/s/src/generated/RoleManagement/DirectoryNamespace/DirectoryRequestBuilder.cs:line 95
```
Version: 1.0.0-rc.2
Build: arm64
MacOS version: 13.5

**Comment by calebkiage** [comment]
What's the output when you add the `--debug` flag?
e.g. `mgc identity get --debug`

**Comment by bgmonroe** [comment]
``` sh
$ mgc identity get --debug
[Informational] Azure-Identity: DeviceCodeCredential.GetToken invoked. Scopes: [ https://graph.microsoft.com/.default ] ParentRequestId:
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] MSAL MSAL.NetCore with assembly version '4.56.0.0'. CorrelationId(04523cfc-d52f-4816-a286-e4423d675cb9)
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] === AcquireTokenSilent Parameters ===
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] LoginHint provided: False
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Account provided: True
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] ForceRefresh: False
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9]
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.microsoft.com/.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 04523cfc-d52f-4816-a286-e4423d675cb9
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] === Token Acquisition (SilentRequest) started:
	 Scopes: https://graph.microsoft.com/.default
	Authority Host: login.microsoftonline.com
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [Region discovery] Not using a regional authority.
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Access token has expired or about to expire. [Current time (11/09/2023 20:54:00) - Expiration Time (11/09/2023 19:37:37 +00:00) - Extended Expiration Time (11/09/2023 19:37:37 +00:00)]
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [Region discovery] Not using a regional authority.
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [Region discovery] Not using a regional authority.
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [FindRefreshTokenAsync] Refresh token found in the cache? - True
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [Instance Discovery] Instance discovery is enabled and will be performed
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [Region discovery] Not using a regional authority.
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:00Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Fetching instance discovery from the network from host login.microsoftonline.com.
[Informational] Azure-Core: Request [caa2114e-11d5-4a42-9ada-9bc433f7fdff] GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:caa2114e-11d5-4a42-9ada-9bc433f7fdff
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.10.3 (.NET 7.0.12; Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000)
client assembly: Azure.Identity
[Informational] Azure-Core: Response [caa2114e-11d5-4a42-9ada-9bc433f7fdff] 200 OK (00.3s)
Cache-Control:max-age=86400, private
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Access-Control-Allow-Origin:REDACTED
Access-Control-Allow-Methods:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:93854168-774b-44af-aad2-46f305670300
x-ms-ests-server:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Thu, 09 Nov 2023 20:54:00 GMT
Content-Type:application/json; charset=utf-8
Content-Length:980

[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Authority validation enabled? True.
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Authority validation - is known env? True.
[Informational] Azure-Core: Request [d7a10bbc-2928-49dc-b485-089493de6af9] POST https://login.microsoftonline.com/dd3dfd2f-6a3b-40d1-9be0-bf8327d81c50/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
x-anchormailbox:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
Content-Type:application/x-www-form-urlencoded
x-ms-client-request-id:d7a10bbc-2928-49dc-b485-089493de6af9
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.10.3 (.NET 7.0.12; Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000)
client assembly: Azure.Identity
[Informational] Azure-Core: Response [d7a10bbc-2928-49dc-b485-089493de6af9] 200 OK (00.2s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:70334202-8328-424e-b7de-93a957d10900
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Thu, 09 Nov 2023 20:54:00 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:5169

[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Checking client info returned from the server..
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Saving token response to cache..
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [Region discovery] Not using a regional authority.
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [SaveTokenResponseAsync] Saving AT in cache and removing overlapping ATs...
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Looking for scopes for the authority in the cache which intersect with https://graph.microsoft.com/.default
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Intersecting scope entries count - 1
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Matching entries after filtering by user - 1
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [SaveTokenResponseAsync] Saving Id Token and Account in cache ...
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [SaveTokenResponseAsync] Saving RT in cache...
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] IsLegacyAdalCacheEnabled: yes
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] [AdalCacheOperations] Serializing token cache with 1 items.
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9]
	=== Token Acquisition finished successfully:
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9]  AT expiration time: 11/9/2023 10:09:47 PM +00:00, scopes: openid profile email https://graph.microsoft.com/AppRoleAssignment.ReadWrite.All https://graph.microsoft.com/Directory.Read.All https://graph.microsoft.com/User.Read https://graph.microsoft.com/User.Read.All https://graph.microsoft.com/.default. source: IdentityProvider
[Informational] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 [2023-11-09 20:54:01Z - 04523cfc-d52f-4816-a286-e4423d675cb9] Fetched access token from host login.microsoftonline.com.
[Informational] Azure-Identity: DeviceCodeCredential.GetToken succeeded. Scopes: [ https://graph.microsoft.com/.default ] ParentRequestId:  ExpiresOn: 2023-11-09T22:09:47.2475730+00:00
dbug: Microsoft.Graph.Cli.Core.Http.LoggingHandler[1]

      Request:

      GET https://graph.microsoft.com/v1.0/identity HTTP/1.1
      Accept: application/json; q=1
      Authorization: [PROTECTED]
      FeatureFlag: 00000043
      Cache-Control: no-store, no-cache
      User-Agent: kiota-dotnet/1.1.1
      SdkVersion: graph-cli-1.0/1.0.0, graph-dotnet-core/3.0.11 (featureUsage=0000002B; hostOS=Unix 13.5.0; hostArch=Arm64; runtimeEnvironment=.NET 7.0.12;)
      client-request-id: f1826375-f01a-4ffe-9e39-d5e77ac1d5b2



dbug: Microsoft.Graph.Cli.Core.Http.LoggingHandler[2]

      Response:

      HTTP/1.1 404 Not Found
      Cache-Control: no-cache
      Transfer-Encoding: chunked
      Vary: Accept-Encoding
      Strict-Transport-Security: max-age=31536000
      request-id: ba76bb89-dcf8-401a-a85b-302ef663d4aa
      client-request-id: f1826375-f01a-4ffe-9e39-d5e77ac1d5b2
      x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US 2","Slice":"E","Ring":"1","ScaleUnit":"002","RoleInstance":"MWH0EPF0005A6B0"}}
      Date: Thu, 09 Nov 2023 20:54:01 GMT
      Content-Type: application/json
      Content-Encoding: gzip

      {"error":{"code":"UnknownError","message":"{\"message\":\"No HTTP resource was found that matches the request URI 'https://cpim.windows.net/graph/identity'.\",\"messageDetail\":\"No type was found that matches the controller named 'identity'.\",\"stackTrace\":null}","innerError":{"date":"2023-11-09T20:54:01","request-id":"ba76bb89-dcf8-401a-a85b-302ef663d4aa","client-request-id":"f1826375-f01a-4ffe-9e39-d5e77ac1d5b2"}}}

Unhandled exception: ApiSdk.Models.ODataErrors.ODataError: Exception of type 'ApiSdk.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at ApiSdk.Identity.IdentityRequestBuilder.<>c__DisplayClass3_0.<<BuildGetCommand>b__1>d.MoveNext() in /home/vsts/work/1/s/src/generated/Identity/IdentityRequestBuilder.cs:line 141
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c__DisplayClass0_0.<<UseRequestAdapter>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Graph.Cli.Program.<>c.<<Main>b__2_2>d.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 74
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Graph.Cli.Program.<>c__DisplayClass3_0.<<BuildCommandLine>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 137
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c.<<RegisterCommonServices>b__2_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c__DisplayClass3_0.<<RegisterHeadersOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by bgmonroe** [comment]
Looks like the "identity" sub-args hits an API endpoints that don't exist (publicly I assume).  The other sub-arg (role-management directory get)  doesn't actually support any HTTP verbs and requires (according to the API docs) roleDefinitions be added to the constructed API endpoint.  Anyways, it seems like there are two issues at play here.
1. Error handling from HTTP 40x errors should be handled better than a "Unhandled exception."
2. The supported/available sub-commands don't all seem to align with the API endpoint's capabilities.

**Comment by calebkiage** [comment]
Hello @bgmonroe, thanks for the additional information. I'm investigating the error message format. It shouldn't be an unhandled exception.

You might be right about the subcommands. we have some cases of endpoints defined in the OpenAPI that shouldn't be, for example #370. I'll confirm your specific situation.

What scenario are you trying to achieve so I can try to find an alternative for you?

**Comment by bgmonroe** [comment]
Thanks for your super quick followups!  TBH, I just downloaded mgc and was mostly just kicking the tires.  
Saying that, however, the path that got me to the msgraph CLI, was to gather information on apps in my tenant that have consented MS Graph access and report on what that access is.  I can get there partially with the az cli tool via:
``` sh
$ az ad app list --all -o json --query "[?requiredResourceAccess[?resourceAppId=='00000003-0000-0000-c000-000000000000']].{Name:displayName, Access:requiredResourceAccess[?resourceAppId=='00000003-0000-0000-c000-000000000000'].resourceAccess[].id}"
```
But that returns App Role IDs (GUIDs) which, on their own, isn't very helpful, so I wanted to look at other tools to look up/pair the app role GUIDs to their displayName.  However it doesn't look like this will be possible with a single API call regardless of how convoluted the JMESPath query is, considering the app roles are only defined and available via the `00000003-0000-0000-c000-000000000000` service principal endpoint.  Oh well.  I'm super happy to find the `mgc` command and look forward to it maturing.

**Comment by calebkiage** [comment]
Have you tried [Microsoft Graph Support](https://developer.microsoft.com/en-us/graph/support)? I think they might be able to help you find the right API. After which you can use the snippets support in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer/) to get the right CLI command

**Comment by bgmonroe** [comment]
Thanks for the recommendation, Caleb.  I was able to take the "one-liner" as far as I could (including querying the Graph resource for it's appRoles, transforming it and then remapping the above output with the role names....However saying that, it looks like the only way to get the true list of Admin Consented Graph perms is to hit the private API  https://main.iam.ad.ext.azure.com/api/Permissions as the above's output includes both Admin Consented permissions as well as Admin Consent requested (but not truly consented).  I guess I'll have to write some Python. :D

**Comment by calebkiage** [comment]
I hope you were successful in getting the information you needed from the API. If you had trouble still, feel free to reopen the issue with any additional information and if possible, a link to a graph support ticket you opened for further help.

**Comment by bgmonroe** [comment]
I did via other methods but not sure why this issue was closed as it pertains to error handling unless that's been resolved via a recent PR.
