### ISSUE TITLE
Interactive login isn't working

### ISSUE THREAD

**Issue by hashimaziz1** [microsoftgraph/msgraph-cli#388]
I ran the interactive login and successfully logged into my personal Microsoft account with:

```
mgc login --strategy InteractiveBrowser
```

But when I tried to run:

```
mgc users todo lists tasks list --user-id 0d3cabe9c269adce --todo-task-list-id AQMkADAwATY0MDABLTg0YWUtODY4ZC0wMAItMDAKAC4AAAPj8cHh2dxiQKaJjMS6ouE0AQBd9mrgTid1TLHJIArzzYxJAANeXC5nAAAA --filter "Status+ne+'Completed'"
```

I got the following error:

```
[Error] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Microsoft Windows 10.0.19045 [2023-1
1-09 19:41:20Z - 5e47d3d4-1ed6-4aad-bd28-de798da50da7] === Token Acquisition (1007) failed.
        Host: login.microsoftonline.com.
[Error] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Microsoft Windows 10.0.19045 [2023-1
1-09 19:41:20Z - 5e47d3d4-1ed6-4aad-bd28-de798da50da7] Exception type: Microsoft.Identity.Client.MsalUiRe
quiredException
, ErrorCode: invalid_grant
HTTP StatusCode 400
CorrelationId 5e47d3d4-1ed6-4aad-bd28-de798da50da7

[Error] Azure-Identity: False MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Microsoft Windows 10.0.19045 [2023-1
1-09 19:41:20Z - 5e47d3d4-1ed6-4aad-bd28-de798da50da7] Exception type: Microsoft.Identity.Client.MsalUiRe
quiredException
, ErrorCode: invalid_grant
HTTP StatusCode 400
CorrelationId 5e47d3d4-1ed6-4aad-bd28-de798da50da7

   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken can
cellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToke
n)
Unhandled exception: Azure.Identity.AuthenticationRequiredException: Interactive authentication is needed
 to acquire token. Call Authenticate to interactively authenticate.
 ---> MSAL.NetCore.4.56.0.0.MsalUiRequiredException:
        ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS70000: The request was denied because one or mor
e scopes requested are unauthorized or expired. The user must first sign in and grant the client applicat
ion access to the requested scope. Trace ID: a1d23cbe-dd95-4cd8-a6d7-cae0528b6702 Correlation ID: 5e47d3d
4-1ed6-4aad-bd28-de798da50da7 Timestamp: 2023-11-09 19:41:20Z
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken can
cellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToke
n)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTok
enCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken can
cellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenP
arameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenSilentCoreAsync(String[] scopes, String claims, Authent
icationRecord record, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationTo
ken)
   at Azure.Identity.MsalPublicClient.AcquireTokenSilentAsync(String[] scopes, String claims, Authenticat
ionRecord record, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext re
questContext, CancellationToken cancellationToken)
        StatusCode: 400
        ResponseBody: {"error":"invalid_grant","error_description":"AADSTS70000: The request was denied b
ecause one or more scopes requested are unauthorized or expired. The user must first sign in and grant th
e client application access to the requested scope. Trace ID: a1d23cbe-dd95-4cd8-a6d7-cae0528b6702 Correl
ation ID: 5e47d3d4-1ed6-4aad-bd28-de798da50da7 Timestamp: 2023-11-09 19:41:20Z","error_codes":[70000],"ti
mestamp":"2023-11-09 19:41:20Z","trace_id":"a1d23cbe-dd95-4cd8-a6d7-cae0528b6702","correlation_id":"5e47d
3d4-1ed6-4aad-bd28-de798da50da7","error_uri":"https://login.microsoftonline.com/error?code=70000"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 5e47d3d4-1ed6-4aad-bd28-de798da50da7
x-ms-request-id: a1d23cbe-dd95-4cd8-a6d7-cae0528b6702
x-ms-ests-server: 2.1.16693.3 - FRC ProdSlices
x-ms-clitelem: 1,70000,0,,
X-XSS-Protection: 0
Set-Cookie: fpc=AhsoZyQrHvJImxrNjqt9iKt4ZtvpAQAAAN8s39wOAAAA; expires=Sat, 09-Dec-2023 19:41:20 GMT; path
=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly,
stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Thu, 09 Nov 2023 19:41:20 GMT

   --- End of inner exception stack trace ---
   at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext re
questContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, B
oolean isCredentialUnavailable)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext re
questContext, CancellationToken cancellationToken)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenAsync(TokenRequestContext requestContext, Cance
llationToken cancellationToken)
   at Microsoft.Kiota.Authentication.Azure.AzureIdentityAccessTokenProvider.GetAuthorizationTokenAsync(Ur
i uri, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken)
   at Microsoft.Kiota.Abstractions.Authentication.BaseBearerTokenAuthenticationProvider.AuthenticateReque
stAsync(RequestInformation request, Dictionary`2 additionalAuthenticationContext, CancellationToken cance
llationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInfor
mation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims, B
oolean isStreamResponse)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformati
on requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Cli.Commons.IO.BasePagingService.GetPagedDataAsync(Func`3 requestExecutorAsync, Pag
eLinkData pageLinkData, Boolean fetchAllPages, CancellationToken cancellationToken)
   at ApiSdk.Users.Item.Todo.Lists.Item.Tasks.TasksRequestBuilder.<>c__DisplayClass4_0.<<BuildListCommand
>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d
.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReport
ing>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c__DisplayClass0_0.<<UseRequestAd
apter>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Graph.Cli.Program.<>c.<<Main>b__2_2>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Graph.Cli.Program.<>c__DisplayClass3_0.<<BuildCommandLine>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c.<<RegisterCommonServices>b__2_0
>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Kiota.Cli.Commons.Extensions.CommandBuilderExtensions.<>c__DisplayClass3_0.<<RegisterHead
ersOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.Move
Next()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b_
_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>
b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNex
t()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b
__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.Mo
veNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>
b__0>d.MoveNext()
```

Is this something to do with me not having an Azure account? Is one required to use the CLI?

It's also worth noting that the register app link from the README is currently [dead](https://github.com/microsoftgraph/msgraph-cli/blob/main/register-app.md).

**Comment by calebkiage** [comment]
Hello @hashimaziz1,

Could you try adding the [`Tasks.Read` scope](https://learn.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&tabs=http) to your login command first?

```
mgc login --strategy InteractiveBrowser --scopes Tasks.Read
```

**Comment by hashimaziz1** [comment]
Hi Caleb, thanks for the quick response, sure enough that does fix the issue - the `scope` requirement should probably be added to the README because that's where I was getting the initial command from. 

As an aside, do you have a quick idea why either `--select Title` or the equivalent via the Graph API endpoint/Graph Explorer are not supported for To Do list items? I thought it'd be possible to grab just the titles of To-Do list tasks but it returns a very cryptic error:

```
{"error":{"code":"invalidRequest","message":"Invalid request","innerError":{"code":"RequestBroker--ParseU
ri","date":"2023-11-09T23:50:36","request-id":"10e900a8-270b-4f6c-a17a-c67fa8d7f590","client-request-id":
"d616c57f-aa88-43cf-8760-025e4cac9854"}}}
```

Is this expected with a known reason, or a bug I should report?

**Comment by calebkiage** [comment]
Good to hear that your problem got solved. Permissions is a QoL enhancement we plan on adding in the near future. In the meantime, Graph Explorer can show you what scopes are available if you know the URL.

I think it's possible that the endpoint doesn't actually support `$select`. @irvinesunday, can you chime in on this?
